### ISSUE TITLE
Drop or improve Maven support?

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#201]
### Status Quo:
We push releases of JavaSMT regularly into the Maven repository.
However, most of current maven release are broken (for quite a long time, since d066c19dbf489fad5152f9c6e66364179a5ba431) due to a missing dependency for java-cup (required by Princess).

Side note: Princess actually request a different version of java-cup, but works with the TUM-version as well. This just makes Maven complex, as there is no TUM-version of java-cup in the Maven repository.

### To discuss:
It is nice to have to provide a simple way of using JavaSMT via Maven. However, is there any benefit for us?
Nobody ever complained about the broken dependency, thus the number of users might be small (cause or effect?).
Even for our own software (such as sosy-common), missing Maven dependencies are only noticed when we check it.
There is no CI (#79) and other issues related to Maven have been open for a long time (#88, #67).

- The easiest way would be dropping it completely.
- The more complex way would be a complete revisit of Maven and a proper integration, i.e., such that more solvers are available.

**Comment by proteusGIT** [comment]
I am currently investigating whether to use java-smt.
Since my project already uses maven and not ivy, this would be the best choice for me.
I installed it yesterday and used Z3 on some formula and everything seemed to work (at least for Z3).

**Comment by kfriedberger** [comment]
Our plans are not yet fixed for Maven. This entry is just a status update.

### Cons:
The maintenance effort to support more build systems over a longer time span is quite high and has no direct benefit for our own projects. We need to keep knowledge about Maven in our team.

### Pro:
Maven is one of the most-used build systems for Java software.
Thus, for many other developers, proper Maven support is beneficial.

Lets start with a list of steps that would be needed for a better Maven support:
- [ ] fix the missing JavaCup, e.g., upload it in the namespace of `sosy-lab` or switch to the previous version.
In either case, we need to update the automatically created `pom.xml` file.
- [ ] upload at least a newer Z3 into the Maven repository. The old one there is outdated, unsupported, in the namespace of `sosy-lab`, and is reported by search engines as first match for `z3 maven`. This might be an easy task, as soon as the pom-template for Z3 is written.
- [ ] as soon as we know how to deal with Z3, other solvers should be easy. Our priority might be MathSAT and CVC4.
- [ ] we need to create a test application using JavaSMT from Maven to test our application (see #79). If we additionally manage to implement a Maven-based web application for JavaSMT, we could solve #205. Example: something like https://rise4fun.com/z3, but with less SMTLIB commands, including a table for available solvers and their features.
- [ ] Maven seems to also work for Windows (and MacOS). We might need to support those systems, too.

**Comment by uncttao** [comment]
This is a huge issue for us. We had to manually include jar files in our project due to the broken dependencies.

**Comment by kfriedberger** [comment]
As we do not maintain our own Maven repository, we depend on external teams (mostly developers of SMT solver) to update their software correctly or at least regularly. Having our own Maven repository might also require to keep the packages consistant with the central Maven repository.

A first step was done:
I added a fix for the broken Princess dependency: 3cef0f6a0f12104f89eccb5d022a1ca867d49511.

However, we currently use an updated version of SMTInterpol ([2.5-715-g3a7695dc](https://svn.sosy-lab.org/software/ivy/repository/de.uni-freiburg.informatik.ultimate/smtinterpol/)) that is only available in our own Ivy repository. We require this updated version for our own software. The tool developers did not update their Maven release [since Dec 2019](https://mvnrepository.com/artifact/de.uni-freiburg.informatik.ultimate/smtinterpol).
Publishing our own version of SMTInterpol under the groupId `sosy-lab` seems wrong to me and might cause some still unknown development overhead in dependency management of Maven. So this dependency is now broken for Maven. I contacted the developers, maybe they provide an updated Maven version soon.

For SMT solvers with multiple files and e.g. native binaries, I do not yet know the process of publishing them into Maven.
As far as I found out, each Maven modul can only consists of a single file. Most of our SMT solvers depend on a jar file and multiple native libraries (e.g., Z3 depends on `com.microsoft.z3.jar`, `libz3java.so`, and `libz3.so`). 
Additionally, packaging an application as war-file including native libraries, such that they are found automatically on the target system, is still unknown to me.

**Comment by breandan** [comment]
I was able to get around this by excluding the transitive dependencies (nothing seemed to break):

```
implementation("org.sosy-lab:java-smt:3.6.0") {
    // Remove pending: https://github.com/sosy-lab/java-smt/issues/201
    exclude(group = "uuverifiers", module = "princess_2.13")
    exclude(group = "edu.tum.cs", module = "java-cup")
}
```

**Comment by kfriedberger** [comment]
With JavaSMT `3.6.1` the broken dependency is fixed.

**Comment by breandan** [comment]
In which repository is the `uuverifiers:princess_2.13:2020-09-18-assertionless` artifact hosted? It appears that `edu.tum.cs:java-cup` can be resolved, but Maven is still unable to locate `uuverifiers:princess_2.13`.

**Comment by kfriedberger** [comment]
Our POM template also contains this information, but it seems to be outdated:
https://github.com/sosy-lab/java-smt/blob/e9f13353746cc47746e507d4f5d00ae09eb30e98/pom_template.xml#L72-L78

Thanks for reporting.

**Comment by kfriedberger** [comment]
**Current status**: @baierd is working on that topic.
We will improve Maven support for solvers like MathSAT and Z3.
The plan is to provide an example project for Maven (a plain Java application and/or a web-app for Tomcat)
that include all necessary documentation like the commands for Maven and the corresponding plugins.

**Comment by baierd** [comment]
Update:
-Providing Z3/Mathsat5 binaries is no issue (most likely even for Windows, i still need to test the build process for Windows though)
-Building/Testing /w Z3/Mathsat5 is no problem as well. There are some small things that need to be configured in every Maven project /w those 2 librarys though.
-It is necassary to provide the build Project with the classpath to the native librarys.
-It is not possible to pack the native libs into the jar at the moment. (This is due to our commons-lib that uses loadLibrary(). We would need loadFile() for this in JavaSMT/commons and @kfriedberger and probably @PhilippWendler have to decide wether this will be provided or not)
-A Tomcat based web application is possible /w JavaSMT and Z3/Mathsat5. And it is possible to pack the native libs into a war file. 

I will provide working examples and a tutorial shortly.

**Comment by kfriedberger** [comment]
Short: Maven support was improved.

Long answer:
Now we provide several solvers (mostly for Linux, some even for Windows) within Maven.
Please take a look at the [documentation](https://github.com/sosy-lab/java-smt/blob/master/doc/Getting-started.md#automatic-installation-from-maven-central-possibly-outdated), an [example application](https://github.com/sosy-lab/java-smt/tree/master/doc/Example-Maven-Project) and an [example webapp](https://github.com/sosy-lab/java-smt/tree/master/doc/Example-Maven-Web-Project) based on Maven.

**Comment by breandan** [comment]
Tried using the latest dependency on Maven Central `org.sosy-lab:java-smt:3.7.0-61-gea80187e`, but it would still seem to be necessary to add an external repository `http://logicrunch.research.it.uu.se/maven/` the to fetch the `uuverifiers:princess_2.13:2020-09-18-assertionless` dependency. This causes the following problem when using your library from Gradle:

`Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven6(http://logicrunch.research.it.uu.se/maven/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols.
`

Is there any way to host all artifacts on a common Maven repository?

**Comment by kfriedberger** [comment]
Quick fix:
This third-party dependency is required for the SMT solver `Princess`, as its developer hosts it only there.
If you do not want to run `Princess`, you can exclude this dependency, and also all `Scala`-related libraries.

We will think about the situation and maybe find a better solution, e.g.,
by publishing a copy of Princess in the namespace `sosy-lab` on Maven.

**Comment by kfriedberger** [comment]
Small update from the developers of Princess:
They plan to put Princess on MavenCentral in the future.
So lets wait for that.

**Comment by breandan** [comment]
@kfriedberger It appears that @uuverifiers has now added [Princess](https://github.com/uuverifiers/princess/) to [Maven Central](https://search.maven.org/search?q=Princess).

**Comment by kfriedberger** [comment]
Thanks for the notification.
We already have a branch [`princess_update`](https://github.com/sosy-lab/java-smt/tree/princess-update) for this, where we use the newer Princess from Maven Central. Due to internal improvements in Princess, we are still working on the integration and some bugs, mainly in the components for arrays and models.

**Comment by breandan** [comment]
Thanks for your hard work migrating to Maven and updating Princess! Looking forward to trying this out once it's available.

**Comment by kfriedberger** [comment]
I already published the new release today: version `3.9.0` for Ant/Ivy, `3.9.0-1-g304079c2` for Maven.
The Maven repository internally requires some hours to synchronize.
